name: CI

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  linux:
    name: Run tests on Linux, V version "${{ matrix.v-version }}"
    strategy:
      matrix:
        v-version: [latest, tags/0.2]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch the V version "${{ matrix.v-version }}"
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "vlang/v"
          version: "${{ matrix.v-version }}"
          file: "v_linux.zip"

      - name: Setup V
        run: |
          unzip -q v_linux.zip -d /opt
          /opt/v/v version

      - name: Check the formatting
        run: /opt/v/v test-fmt

      - name: Run tests
        run: /opt/v/v test .

  macos:
    name: Run tests on macOS, V version "${{ matrix.v-version }}"
    strategy:
      matrix:
        v-version: [latest, "0.2"]
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch the V version "${{ matrix.v-version }}"
        uses: tix-factory/release-manager@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          mode: downloadReleaseAsset
          filePath: /tmp/v_macos.zip
          assetName: "v_macos.zip"
          tag: "${{ matrix.v-version }}"
          repo: v
          owner: vlang

      - name: Setup V
        run: |
          unzip -q /tmp/v_macos.zip -d /tmp
          /tmp/v/v version

      - name: Check the formatting
        run: /tmp/v/v test-fmt

      - name: Run tests
        run: /tmp/v/v test .
