name: Check the code formatting and run tests

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  test:
    name: Run tests on Linux, V version "${{ matrix.v-version }}"
    strategy:
      matrix:
        v-version: [latest, tags/0.2]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch the V version "${{ matrix.v-version }}"
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "vlang/v"
          version: "${{ matrix.v-version }}"
          file: "v_linux.zip"

      - name: Setup V
        run: |
          unzip -q v_linux.zip -d /opt
          /opt/v/v version

      - name: Check the formatting
        run: /opt/v/v test-fmt

      - name: Run tests
        run: /opt/v/v test .
